---
name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']
        browser: ['chrome', 'firefox']
        gemfile: ['Gemfile', 'gemfiles/Gemfile.low_spec', 'gemfiles/Gemfile.webdriver_alpha']
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      BROWSER: ${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: '2.2.33'
          bundler-cache: true
      - run: bundle exec rspec
      - run: bundle exec cucumber
      - run: bundle exec rubocop
